baseURL = 'https://aoc.maymeow.dev/'
languageCode = 'en-us'
title = 'ðŸŽ„ Advent of Code by May'
theme = 'nostyleplease'
description = 'My solutions for advent of code puzzles'

[markup]
  [markup.highlight]
    style = 'RPGLE'